// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zydhuofdkeqyoccpizub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5ZGh1b2Zka2VxeW9jY3BpenViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3OTUzMTQsImV4cCI6MjA3NDM3MTMxNH0.0b3NMk7oR7pDqwUqYoivutYcqRtNtukfi-gOrIXtBXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});